
function Text() {
  return (
    <div style={{marginLeft:"150px", marginTop:"100px"}}>
    <div>Text   1</div>
    <div>Text   2</div>
    <div>Text   3</div>
    <div>Text   4</div>
    <div>Text   5</div>
    <div>Text   6</div>
    <div>Text   7</div>
    <div>Text   8</div>
    <div>Text   9</div>
    <div>Text   10</div>
    <div>Text   11</div>
    <div>Text   12</div>
    <div>Text   13</div>
    <div>Text   14</div>
    <div>Text   15</div>
    <div>Text   16</div>
    <div>Text   17</div>
    <div>Text   18</div>
    <div>Text   19</div>
    <div>Text   20</div>
    <div>Text   21</div>
    <div>Text   22</div>
    <div>Text   23</div>
    <div>Text   24</div>
    <div>Text   25</div>
    <div>Text   26</div>
    <div>Text   27</div>
    <div>Text   28</div>
    <div>Text   29</div>
    <div>Text   30</div>
    <div>Text   31</div>
    <div>Text   32</div>
    <div>Text   33</div>
    <div>Text   34</div>
    <div>Text   35</div>
    <div>Text   36</div>
    <div>Text   37</div>
    <div>Text   38</div>
    <div>Text   39</div>
    <div>Text   40</div>
    <div>Text   41</div>
    <div>Text   42</div>
    <div>Text   43</div>
    <div>Text   44</div>
    <div>Text   45</div>
    <div>Text   46</div>
    <div>Text   47</div>
    <div>Text   48</div>
    <div>Text   49</div>
    <div>Text   50</div>
    <div>Text   51</div>
    <div>Text   52</div>
    <div>Text   53</div>
    <div>Text   54</div>
    <div>Text   55</div>
    <div>Text   56</div>
    <div>Text   57</div>
    <div>Text   58</div>
    <div>Text   59</div>
    <div>Text   60</div>
    <div>Text   61</div>
    <div>Text   62</div>
    <div>Text   63</div>
    <div>Text   64</div>
    <div>Text   65</div>
    <div>Text   66</div>
    <div>Text   67</div>
    <div>Text   68</div>
    <div>Text   69</div>
    <div>Text   70</div>
    <div>Text   71</div>
    <div>Text   72</div>
    <div>Text   73</div>
    <div>Text   74</div>
    <div>Text   75</div>
    <div>Text   76</div>
    <div>Text   77</div>
    <div>Text   78</div>
    <div>Text   79</div>
    <div>Text   80</div>
    <div>Text   81</div>
    <div>Text   82</div>
    <div>Text   83</div>
    <div>Text   84</div>
    <div>Text   85</div>
    <div>Text   86</div>
    <div>Text   87</div>
    <div>Text   88</div>
    <div>Text   89</div>
    <div>Text   90</div>
    <div>Text   91</div>
    <div>Text   92</div>
    <div>Text   93</div>
    <div>Text   94</div>
    <div>Text   95</div>
    <div>Text   96</div>
    <div>Text   97</div>
    <div>Text   98</div>
    <div>Text   99</div>
    <div>Text   100</div>
    <div>Text   101</div>
    <div>Text   102</div>
    <div>Text   103</div>
    <div>Text   104</div>
    <div>Text   105</div>
    <div>Text   106</div>
    <div>Text   107</div>
    <div>Text   108</div>
    <div>Text   109</div>
    <div>Text   110</div>
    <div>Text   111</div>
    <div>Text   112</div>
    <div>Text   113</div>
    <div>Text   114</div>
    <div>Text   115</div>
    <div>Text   116</div>
    <div>Text   117</div>
    <div>Text   118</div>
    <div>Text   119</div>
    <div>Text   120</div>
    <div>Text   121</div>
    <div>Text   122</div>
    <div>Text   123</div>
    <div>Text   124</div>
    <div>Text   125</div>
    <div>Text   126</div>
    <div>Text   127</div>
    <div>Text   128</div>
    <div>Text   129</div>
    <div>Text   130</div>
    <div>Text   131</div>
    <div>Text   132</div>
    <div>Text   133</div>
    <div>Text   134</div>
    <div>Text   135</div>
    <div>Text   136</div>
    <div>Text   137</div>
    <div>Text   138</div>
    <div>Text   139</div>
    <div>Text   140</div>
    <div>Text   141</div>
    <div>Text   142</div>
    <div>Text   143</div>
    <div>Text   144</div>
    <div>Text   145</div>
    <div>Text   146</div>
    <div>Text   147</div>
    <div>Text   148</div>
    <div>Text   149</div>
    <div>Text   150</div>
    <div>Text   151</div>
    <div>Text   152</div>
    <div>Text   153</div>
    <div>Text   154</div>
    <div>Text   155</div>
    <div>Text   156</div>
    <div>Text   157</div>
    <div>Text   158</div>
    </div>
  )
}

export default Text